spring.application.name=GeekText
spring.datasource.url=jdbc:postgresql://localhost:5432/geektext
spring.datasource.username=postgres
spring.datasource.password=GeekText

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
