spring.application.name=Group_24_Project

spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=apppass


spring.jpa.open-in-view=false

//spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=false
//spring.jpa.hibernate.ddl-auto=update
